version: 1.0.{build}
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- ps: >-
    cat (src\RedBear.Log4View.AzureServiceBus.Target.nuspec) | % { $_ -replace "@version", $env:appveyor_build_version } > src\RedBear.Log4View.AzureServiceBus.Target.nuspec

    nuget restore src\RedBear.Log4View.AzureServiceBus.Target.sln

build:
  publish_nuget: true
  verbosity: minimal
notifications:
- provider: Slack
  incoming_webhook:
    secure: Mtm90XxM7T+5NlCQZ6xlQMqJ4I88JWmn6Vf3CgsTmhmcWPZHzIX5v5UxiOxtXqlpqWYVaXLCBsxU3vCMw+Ru9rhtrVag0a9ZvTzg59uU4KM=
artifacts:
- path: src\bin\Release\RedBear.Log4View.AzureServiceBus.Target.dll
deploy:
- provider: NuGet
  api_key:
    secure: uMFJIRdMd8WBrUSsuBDxCm/Uo8/PK22UwPZtCJm5s6qr+3BWzin/XHDx3+hZU+Xz
  artifact: /.*\.nupkg/